"""Industry-first research orchestration primitives."""

from .models import (
    CompanyCandidate,
    CompanyDataTier,
    IndustryRadarSnapshot,
    IndustryState,
    ResourcePolicy,
    ScanResult,
)
from .pipeline import IndustryFirstDiscovery
from .report import render_scan_html, render_scan_markdown
from .company_research import (
    CompanyResearchAssembler,
    CompanyResearchQuery,
    CompanyResearchSnapshot,
    snapshot_from_config,
)
from .industry_radar import IndustryRadarCollection, IndustryRadarCollector
from .data_sources import (
    AkshareDataSourceAdapter,
    BaoStockDataSourceAdapter,
    DataSourceAttempt,
    DataSourceExhaustedError,
    DataSourceHealth,
    DataSourceRouter,
    EastmoneyDataSourceAdapter,
    FreeDataSourcePolicy,
    PublicHttpDataSourceAdapter,
    RoutedDataResult,
    default_data_source_router,
    default_free_data_adapters,
)
from .research_assets import (
    ResearchAssetAdapter,
    ResearchAssetCompanyPool,
    ResearchAssetError,
)
from .security_master import (
    SecurityMasterError,
    build_security_master_snapshot,
    lookup_security_master_company,
    validate_security_master_snapshot,
)
from .company_scope import (
    CompanyScopeError,
    build_company_scope_report,
    validate_company_scope_report,
    scope_item_for_company,
    normalize_scope_reports,
)
from .market_data import (
    MarketDataError,
    build_market_data_snapshot,
    validate_market_data_snapshot,
    extract_market_data_series,
)
from .market_registry import (
    MarketRegistry,
    MarketRegistryError,
    build_market_registry_report,
    validate_market_reference,
)
from .industry_adapters import (
    IndustryAdapterDefinition,
    IndustryAdapterError,
    IndustryAdapterRegistry,
    build_industry_adapter_registry_report,
    build_industry_profile_report,
)
from .evidence import (
    CROSS_VALIDATED,
    COMPANY_CLAIM,
    EvidenceError,
    MARKET_SIGNAL,
    MODEL_ASSUMPTION,
    UNKNOWN,
    VERIFIED_FACT,
    build_evidence,
    build_evidence_bundle,
    build_evidence_input_bundle,
    build_model_assumption,
    build_research_artifact,
    build_research_candidate_set,
    build_scorecard_artifact,
    build_source_document,
    reconcile_evidence,
    validate_evidence_cutoff,
)
from .research_execution import (
    ResearchExecutionError,
    build_execution_audit,
    build_llm_run,
    build_research_execution_plan,
    build_research_request,
)
from .capability_matrix import (
    CapabilityMatrixError,
    build_capability_gap,
    build_capability_matrix,
)
from .opportunity_quality import (
    OpportunityQualityError,
    build_opportunity_quality_report,
)
from .decision_lifecycle import (
    DecisionLifecycleError,
    build_decision_lifecycle,
    build_decision_lifecycle_event,
)
from .research_version import (
    ResearchVersionError,
    build_research_version,
    build_research_version_comparison,
    build_research_version_from_pipeline,
    build_research_version_replay,
    validate_research_version,
)
from .research_impact import (
    ResearchImpactError,
    build_research_impact_queue,
    validate_research_impact_queue,
)
from .announcement_templates import (
    AnnouncementTemplateError,
    get_template,
    load_template_catalog,
    parse_announcement_input,
    validate_template_catalog,
)
from .product_profit_bridge import (
    ProductProfitBridgeError,
    build_product_profit_bridge_report,
    validate_product_profit_bridge_report,
)
from .product_lifecycle import (
    ProductLifecycleError,
    build_product_lifecycle_report,
    validate_product_lifecycle_report,
)
from .financial_model import (
    FinancialModelError,
    build_financial_model_report,
    validate_financial_model_report,
)
from .futures_tracking import (
    FuturesTrackingError,
    build_futures_tracking_report,
)
from .public_draft import (
    PublicDraftError,
    build_public_draft,
    validate_public_draft,
)
from .source_health import (
    SourceHealthError,
    build_source_health_snapshot,
    validate_source_health_snapshot,
)
from .data_refresh import (
    DATA_REFRESH_INPUT_SCHEMA_VERSION,
    DATA_REFRESH_SCHEMA_VERSION,
    DataRefreshError,
    build_data_source_refresh,
    validate_data_source_refresh,
)
from .refresh_evidence import (
    REFRESH_EVIDENCE_INPUT_SCHEMA_VERSION,
    REFRESH_EVIDENCE_SCHEMA_VERSION,
    RefreshEvidenceError,
    build_refresh_evidence_gate,
    validate_refresh_evidence_gate,
)
from .data_refresh_tracking import (
    DATA_REFRESH_TRACKING_SCHEMA_VERSION,
    DataRefreshTrackingError,
    build_data_refresh_tracking_report,
    validate_data_refresh_tracking_report,
)
from .task_resolution import (
    TaskResolutionError,
    resolve_research_task,
    validate_research_task,
)
from .third_party_components import (
    CamelotDocumentParser,
    DocumentParserAdapter,
    PdfplumberDocumentParser,
    PypdfDocumentParser,
    ThirdPartyComponentError,
    ThirdPartyComponentRegistry,
    build_component_health_snapshot,
    build_component_registry,
    build_component_registration_from_candidate,
    build_performance_metrics_report,
    parse_local_document,
    validate_component_health_snapshot,
    validate_component_registry_links,
    validate_component_registry,
    validate_performance_metrics_report,
)
from .third_party_candidate_review import (
    ThirdPartyCandidateReviewError,
    build_candidate_review,
    build_candidate_review_event,
    build_candidate_review_projection,
    validate_candidate_review,
    validate_candidate_review_event,
    validate_candidate_review_projection,
)
from .futures_simulation import (
    FuturesSimulationError,
    build_futures_simulation,
    replay_futures_simulation,
)

__all__ = [
    "CompanyCandidate",
    "CompanyDataTier",
    "IndustryFirstDiscovery",
    "IndustryRadarSnapshot",
    "IndustryState",
    "ResourcePolicy",
    "ScanResult",
    "render_scan_markdown",
    "render_scan_html",
    "CompanyResearchAssembler",
    "CompanyResearchQuery",
    "CompanyResearchSnapshot",
    "snapshot_from_config",
    "IndustryRadarCollection",
    "IndustryRadarCollector",
    "AkshareDataSourceAdapter",
    "BaoStockDataSourceAdapter",
    "DataSourceAttempt",
    "DataSourceExhaustedError",
    "DataSourceHealth",
    "DataSourceRouter",
    "EastmoneyDataSourceAdapter",
    "FreeDataSourcePolicy",
    "PublicHttpDataSourceAdapter",
    "RoutedDataResult",
    "default_data_source_router",
    "default_free_data_adapters",
    "ResearchAssetAdapter",
    "ResearchAssetCompanyPool",
    "ResearchAssetError",
    "SecurityMasterError",
    "build_security_master_snapshot",
    "lookup_security_master_company",
    "validate_security_master_snapshot",
    "CompanyScopeError",
    "build_company_scope_report",
    "validate_company_scope_report",
    "scope_item_for_company",
    "normalize_scope_reports",
    "MarketDataError",
    "build_market_data_snapshot",
    "validate_market_data_snapshot",
    "extract_market_data_series",
    "MarketRegistry",
    "MarketRegistryError",
    "build_market_registry_report",
    "validate_market_reference",
    "IndustryAdapterDefinition",
    "IndustryAdapterError",
    "IndustryAdapterRegistry",
    "build_industry_adapter_registry_report",
    "build_industry_profile_report",
    "EvidenceError",
    "VERIFIED_FACT",
    "CROSS_VALIDATED",
    "COMPANY_CLAIM",
    "MARKET_SIGNAL",
    "MODEL_ASSUMPTION",
    "UNKNOWN",
    "build_source_document",
    "build_evidence",
    "build_evidence_bundle",
    "build_evidence_input_bundle",
    "build_model_assumption",
    "build_research_artifact",
    "build_research_candidate_set",
    "build_scorecard_artifact",
    "reconcile_evidence",
    "validate_evidence_cutoff",
    "ResearchExecutionError",
    "build_research_request",
    "build_research_execution_plan",
    "build_llm_run",
    "build_execution_audit",
    "CapabilityMatrixError",
    "build_capability_matrix",
    "build_capability_gap",
    "OpportunityQualityError",
    "build_opportunity_quality_report",
    "DecisionLifecycleError",
    "build_decision_lifecycle_event",
    "build_decision_lifecycle",
    "ResearchVersionError",
    "build_research_version",
    "build_research_version_comparison",
    "build_research_version_from_pipeline",
    "build_research_version_replay",
    "validate_research_version",
    "ResearchImpactError",
    "build_research_impact_queue",
    "validate_research_impact_queue",
    "AnnouncementTemplateError",
    "get_template",
    "load_template_catalog",
    "parse_announcement_input",
    "validate_template_catalog",
    "ProductProfitBridgeError",
    "build_product_profit_bridge_report",
    "validate_product_profit_bridge_report",
    "ProductLifecycleError",
    "build_product_lifecycle_report",
    "validate_product_lifecycle_report",
    "FinancialModelError",
    "build_financial_model_report",
    "validate_financial_model_report",
    "SourceHealthError",
    "build_source_health_snapshot",
    "validate_source_health_snapshot",
    "DATA_REFRESH_INPUT_SCHEMA_VERSION",
    "DATA_REFRESH_SCHEMA_VERSION",
    "DataRefreshError",
    "build_data_source_refresh",
    "validate_data_source_refresh",
    "REFRESH_EVIDENCE_INPUT_SCHEMA_VERSION",
    "REFRESH_EVIDENCE_SCHEMA_VERSION",
    "RefreshEvidenceError",
    "build_refresh_evidence_gate",
    "validate_refresh_evidence_gate",
    "DATA_REFRESH_TRACKING_SCHEMA_VERSION",
    "DataRefreshTrackingError",
    "build_data_refresh_tracking_report",
    "validate_data_refresh_tracking_report",
    "TaskResolutionError",
    "resolve_research_task",
    "validate_research_task",
    "ThirdPartyComponentError",
    "ThirdPartyComponentRegistry",
    "DocumentParserAdapter",
    "PypdfDocumentParser",
    "PdfplumberDocumentParser",
    "CamelotDocumentParser",
    "build_component_registry",
    "build_component_registration_from_candidate",
    "validate_component_registry",
    "build_component_health_snapshot",
    "validate_component_health_snapshot",
    "validate_component_registry_links",
    "parse_local_document",
    "build_performance_metrics_report",
    "validate_performance_metrics_report",
    "ThirdPartyCandidateReviewError",
    "build_candidate_review",
    "build_candidate_review_event",
    "build_candidate_review_projection",
    "validate_candidate_review",
    "validate_candidate_review_event",
    "validate_candidate_review_projection",
    "FuturesSimulationError",
    "build_futures_simulation",
    "replay_futures_simulation",
]
