"""Build evidence-bound domestic futures fundamental and contract reports.

This module deliberately stops at a research package.  It does not fetch data,
choose a main contract, calculate an intrinsic value, or create a decision
snapshot.  The caller supplies a validated futures identity and a time-cut
evidence package; missing evidence lowers the affected layer instead of being
filled with defaults.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import date, datetime
from math import isfinite
from typing import Any


class FuturesFundamentalsError(ValueError):
    """Raised when a futures fundamentals package cannot be checked safely."""


FUTURES_FUNDAMENTALS_INPUT_SCHEMA_VERSION = "futures-fundamentals-input.v1"
FUTURES_FUNDAMENTALS_SCHEMA_VERSION = "futures-fundamentals-report.v1"
RULE_VERSION = "futures-fundamentals-rules.v1"
IDENTITY_SCHEMA_VERSION = "futures-object-identity.v1"
MARKET_STRUCTURE_SCHEMAS = {
    "market-structure-snapshot.v1",
    "market-structure-comparison.v1",
}

FUNDAMENTAL_FIELDS = (
    "supply_demand_balance",
    "production_and_utilization",
    "imports_exports",
    "inventory_by_location",
    "exchange_inventory_and_warrants",
    "spot_benchmark",
    "production_and_import_cost",
    "industry_margin",
    "basis_and_calendar_spread",
    "term_structure",
    "seasonality",
    "open_interest_and_available_member_positions",
    "delivery_rules_and_warrant_expiry",
)

_VARIETY_FIELDS = (
    "supply_demand_balance",
    "production_and_utilization",
    "imports_exports",
    "inventory_by_location",
    "spot_benchmark",
    "production_and_import_cost",
    "industry_margin",
    "seasonality",
)
_CONTRACT_FIELDS = (
    "spot_benchmark",
    "basis_and_calendar_spread",
    "term_structure",
    "exchange_inventory_and_warrants",
    "delivery_rules_and_warrant_expiry",
)
_VALID_FIELD_STATUSES = {
    "VERIFIED",
    "PARTIAL",
    "UNVERIFIED",
    "MISSING",
    "CONFLICTING",
}
_SERIES_NAMES = (
    "spot_price",
    "contract_settlement",
    "basis",
    "calendar_spread",
    "inventory",
    "exchange_inventory",
    "registered_warrants",
    "open_interest",
    "member_position",
)
_SCENARIOS = ("BEAR", "BASE", "BULL")


def build_futures_fundamentals_report(
    identity_report: Mapping[str, Any],
    evidence_input: Mapping[str, Any],
    *,
    market_structure_report: Mapping[str, Any] | None = None,
    rule_version: str = RULE_VERSION,
    snapshot_id: str = "",
) -> dict[str, Any]:
    """Build F1-F10 results from a validated identity and bounded evidence.

    ``evidence_input`` is intentionally a small JSON contract rather than a
    data-source client.  It can be generated by the exchange/Eastmoney/
    AKShare adapters or filled manually after a source fallback.  The report
    preserves the supplied field values and lineage while only deriving
    arithmetic that is unambiguous from the supplied units and dates.
    """

    _validate_identity(identity_report)
    _validate_input(evidence_input)
    if not rule_version.strip():
        raise FuturesFundamentalsError("rule_version must not be empty")
    if market_structure_report is not None:
        _validate_market_structure(market_structure_report)

    as_of = _parse_date(evidence_input.get("as_of"), "as_of")
    if str(identity_report.get("as_of") or "") and as_of > _parse_date(
        identity_report["as_of"], "identity.as_of"
    ):
        raise FuturesFundamentalsError(
            "evidence as_of cannot exceed the futures identity as_of"
        )

    fields = _normalise_fields(evidence_input.get("fields"), as_of)
    observations = _normalise_observations(evidence_input.get("observations"), as_of)
    scenarios = _normalise_scenarios(evidence_input.get("price_scenarios"), as_of)
    assessments = _normalise_assessments(evidence_input.get("assessments"))

    identity_status = str(identity_report.get("status") or "BLOCKED").upper()
    object_type = str(identity_report.get("object_type") or "").lower()
    contract = identity_report.get("contract") or {}
    if not isinstance(contract, Mapping):
        raise FuturesFundamentalsError("identity contract must be an object")

    derived = _derive_metrics(fields, observations, contract)
    field_gaps = _field_gaps(fields)
    variety_view = _build_variety_view(
        identity_report,
        fields,
        derived,
        assessments,
        field_gaps,
    )
    contract_view = _build_contract_view(
        identity_report,
        fields,
        observations,
        derived,
        assessments,
        field_gaps,
    )
    market_structure = _build_market_structure_view(market_structure_report)
    simulation_view = _build_simulation_view(
        identity_report,
        variety_view,
        contract_view,
        scenarios,
        market_structure,
    )
    phases = _build_phases(
        identity_report=identity_report,
        object_type=object_type,
        fields=fields,
        observations=observations,
        scenarios=scenarios,
        market_structure=market_structure,
        variety_view=variety_view,
        contract_view=contract_view,
        simulation_view=simulation_view,
        field_gaps=field_gaps,
        as_of=as_of,
    )
    report_id = snapshot_id.strip() or str(evidence_input.get("report_id") or "")
    if not report_id:
        report_id = str(identity_report.get("identity_id") or "futures")
    return {
        "schema_version": FUTURES_FUNDAMENTALS_SCHEMA_VERSION,
        "report_id": f"futures-fundamentals-{report_id}",
        "identity_id": str(identity_report.get("identity_id") or ""),
        "object_type": object_type,
        "status": _overall_status(
            identity_status, variety_view, contract_view, simulation_view
        ),
        "as_of": str(evidence_input["as_of"]),
        "research_cutoff": str(evidence_input["as_of"]),
        "exchange": str(identity_report.get("exchange") or ""),
        "variety_id": str(identity_report.get("variety_id") or ""),
        "variety_name": str(identity_report.get("variety_name") or ""),
        "contract": dict(contract),
        "identity_status": identity_status,
        "source": str(evidence_input.get("source") or ""),
        "source_metadata": evidence_input.get("source_metadata") or {},
        "rule_version": rule_version,
        "fields": fields,
        "observations": observations,
        "derived_metrics": derived,
        "price_scenarios": scenarios,
        "assessments": assessments,
        "phases": phases,
        "variety_view": variety_view,
        "contract_view": contract_view,
        "market_structure": market_structure,
        "simulation_view": simulation_view,
        "evidence_gaps": field_gaps,
        "policy": {
            "specific_contract_required_for_simulation": True,
            "continuous_series_research_only": True,
            "missing_spot_inventory_warrant_degrades_conclusion": True,
            "price_scenarios_are_observation_ranges": True,
            "intrinsic_value_generated": False,
            "directional_investment_conclusion": False,
            "decision_snapshot_created": False,
            "automatic_order_included": False,
            "source_data_fetched": False,
            "future_data_rejected": True,
            "read_only": True,
            "review_only": True,
            "execution_enabled": False,
        },
        "read_only": True,
        "review_only": True,
        "investment_conclusion": False,
        "execution_enabled": False,
    }


def _validate_identity(report: Any) -> None:
    if not isinstance(report, Mapping):
        raise FuturesFundamentalsError("identity report must be a JSON object")
    if report.get("schema_version") != IDENTITY_SCHEMA_VERSION:
        raise FuturesFundamentalsError(
            "input identity must be futures-object-identity.v1"
        )
    if str(report.get("object_type") or "").lower() not in {
        "futures_variety",
        "futures_contract",
        "continuous_series",
        "spot_benchmark",
    }:
        raise FuturesFundamentalsError("identity has an unsupported object_type")


def _validate_input(report: Any) -> None:
    if not isinstance(report, Mapping):
        raise FuturesFundamentalsError("evidence input must be a JSON object")
    if report.get("schema_version") != FUTURES_FUNDAMENTALS_INPUT_SCHEMA_VERSION:
        raise FuturesFundamentalsError(
            "input must be futures-fundamentals-input.v1"
        )
    if not str(report.get("as_of") or "").strip():
        raise FuturesFundamentalsError("evidence input as_of is required")
    fields = report.get("fields")
    if fields is not None and not isinstance(fields, Mapping):
        raise FuturesFundamentalsError("fields must be an object")
    observations = report.get("observations")
    if observations is not None and not isinstance(observations, Mapping):
        raise FuturesFundamentalsError("observations must be an object")
    scenarios = report.get("price_scenarios")
    if scenarios is not None and not isinstance(scenarios, Mapping):
        raise FuturesFundamentalsError("price_scenarios must be an object")


def _normalise_fields(raw_fields: Any, as_of: date) -> dict[str, dict[str, Any]]:
    raw_fields = raw_fields if isinstance(raw_fields, Mapping) else {}
    fields: dict[str, dict[str, Any]] = {}
    for field in FUNDAMENTAL_FIELDS:
        raw = raw_fields.get(field)
        fields[field] = _normalise_field(field, raw, as_of)
    # Preserve adapter-specific fields without allowing them to silently
    # replace the required contract fields above.
    for key, raw in raw_fields.items():
        name = str(key)
        if name not in fields:
            fields[name] = _normalise_field(name, raw, as_of)
    return fields


def _normalise_field(field: str, raw: Any, as_of: date) -> dict[str, Any]:
    if raw is None:
        return {
            "status": "MISSING",
            "value": None,
            "unit": "",
            "evidence_ids": [],
            "sources": [],
            "as_of": [],
            "evidence_tiers": [],
            "notes": [],
            "metadata": {},
        }
    if isinstance(raw, Mapping):
        status = str(raw.get("status") or "VERIFIED").upper()
        if status not in _VALID_FIELD_STATUSES:
            raise FuturesFundamentalsError(
                f"unsupported field status for {field}: {status}"
            )
        value = raw.get("value", raw.get("data", raw.get("values")))
        as_of_values = _string_list(raw.get("as_of"))
        if raw.get("observed_at"):
            as_of_values.append(str(raw["observed_at"]))
        for value_as_of in as_of_values:
            _reject_future(value_as_of, as_of, f"fields.{field}.as_of")
        return {
            "status": "MISSING" if not _present(value) else status,
            "value": value,
            "unit": str(raw.get("unit") or ""),
            "evidence_ids": _string_list(raw.get("evidence_ids")),
            "sources": _string_list(raw.get("sources", raw.get("source"))),
            "as_of": list(dict.fromkeys(as_of_values)),
            "evidence_tiers": _string_list(raw.get("evidence_tiers")),
            "notes": _string_list(raw.get("notes")),
            "metadata": dict(raw.get("metadata") or {}),
        }
    return {
        "status": "UNVERIFIED",
        "value": raw,
        "unit": "",
        "evidence_ids": [],
        "sources": [],
        "as_of": [],
        "evidence_tiers": [],
        "notes": ["field was supplied without explicit lineage metadata"],
        "metadata": {},
    }


def _normalise_observations(raw_observations: Any, as_of: date) -> dict[str, list[dict[str, Any]]]:
    raw_observations = raw_observations if isinstance(raw_observations, Mapping) else {}
    result: dict[str, list[dict[str, Any]]] = {}
    for name, raw in raw_observations.items():
        key = str(name)
        if not isinstance(raw, Sequence) or isinstance(raw, (str, bytes, bytearray)):
            raise FuturesFundamentalsError(f"observations.{key} must be a list")
        rows: list[dict[str, Any]] = []
        for index, item in enumerate(raw):
            if not isinstance(item, Mapping):
                raise FuturesFundamentalsError(
                    f"observations.{key}[{index}] must be an object"
                )
            timestamp = item.get("timestamp", item.get("date", item.get("as_of")))
            if timestamp is None:
                raise FuturesFundamentalsError(
                    f"observations.{key}[{index}] requires date or timestamp"
                )
            parsed = _parse_date(timestamp, f"observations.{key}[{index}].date")
            if parsed > as_of:
                raise FuturesFundamentalsError(
                    f"future observation exceeds as_of: observations.{key}[{index}]"
                )
            row = {str(k): v for k, v in item.items()}
            row["date"] = str(timestamp)
            row["_parsed_date"] = parsed.isoformat()
            rows.append(row)
        rows.sort(key=lambda value: value["_parsed_date"])
        if len({row["_parsed_date"] for row in rows}) != len(rows):
            raise FuturesFundamentalsError(f"duplicate dates in observations.{key}")
        result[key] = [
            {key_name: value for key_name, value in row.items() if key_name != "_parsed_date"}
            for row in rows
        ]
    for name in _SERIES_NAMES:
        result.setdefault(name, [])
    return result


def _normalise_scenarios(raw_scenarios: Any, as_of: date) -> dict[str, Any]:
    raw_scenarios = raw_scenarios if isinstance(raw_scenarios, Mapping) else {}
    items: dict[str, dict[str, Any]] = {}
    missing: list[str] = []
    for scenario in _SCENARIOS:
        raw = raw_scenarios.get(scenario, raw_scenarios.get(scenario.lower()))
        if raw is None:
            items[scenario] = {
                "status": "MISSING",
                "range": None,
                "drivers": [],
                "invalidators": [],
                "evidence_ids": [],
            }
            missing.append(scenario)
            continue
        if not isinstance(raw, Mapping):
            raise FuturesFundamentalsError(f"price_scenarios.{scenario} must be an object")
        low = _number(raw.get("low", raw.get("lower")), f"price_scenarios.{scenario}.low")
        high = _number(raw.get("high", raw.get("upper")), f"price_scenarios.{scenario}.high")
        if low is None or high is None:
            raise FuturesFundamentalsError(
                f"price_scenarios.{scenario} requires numeric low and high"
            )
        if low > high:
            raise FuturesFundamentalsError(
                f"price_scenarios.{scenario}.low cannot exceed high"
            )
        scenario_as_of = raw.get("as_of")
        if scenario_as_of:
            _reject_future(str(scenario_as_of), as_of, f"price_scenarios.{scenario}.as_of")
        items[scenario] = {
            "status": "VERIFIED" if raw.get("evidence_ids") or raw.get("sources") else "UNVERIFIED",
            "range": {"low": low, "high": high},
            "drivers": _string_list(raw.get("drivers", raw.get("driver"))),
            "invalidators": _string_list(raw.get("invalidators")),
            "evidence_ids": _string_list(raw.get("evidence_ids")),
            "sources": _string_list(raw.get("sources", raw.get("source"))),
            "as_of": str(scenario_as_of or ""),
        }
    if len(missing) == len(_SCENARIOS):
        status = "INSUFFICIENT"
    elif missing or any(item["status"] == "UNVERIFIED" for item in items.values()):
        status = "PARTIAL"
    else:
        status = "READY"
    return {
        "status": status,
        "scenarios": items,
        "missing": missing,
        "observation_range_only": True,
        "intrinsic_value": None,
    }


def _normalise_assessments(raw_assessments: Any) -> dict[str, Any]:
    if raw_assessments is None:
        return {
            "variety_bias": "NOT_ASSESSED",
            "contract_relative_value": "NOT_ASSESSED",
            "conditional_conclusion": "NOT_ASSESSED",
            "evidence_ids": [],
        }
    if not isinstance(raw_assessments, Mapping):
        raise FuturesFundamentalsError("assessments must be an object")
    return {
        "variety_bias": str(raw_assessments.get("variety_bias") or "NOT_ASSESSED").upper(),
        "contract_relative_value": str(
            raw_assessments.get("contract_relative_value") or "NOT_ASSESSED"
        ).upper(),
        "conditional_conclusion": str(
            raw_assessments.get("conditional_conclusion") or "NOT_ASSESSED"
        ),
        "evidence_ids": _string_list(raw_assessments.get("evidence_ids")),
    }


def _derive_metrics(
    fields: Mapping[str, Mapping[str, Any]],
    observations: Mapping[str, Sequence[Mapping[str, Any]]],
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    spot = _latest_series_number(observations.get("spot_price", ()))
    contract_price = _latest_series_number(
        observations.get("contract_settlement", ()),
        contract_code=str(contract.get("contract_code") or ""),
    )
    if spot is None:
        spot = _number_from_value(fields["spot_benchmark"].get("value"), "spot_benchmark")
    basis = _latest_series_number(observations.get("basis", ()))
    if basis is None and spot is not None and contract_price is not None:
        basis = {
            "date": contract_price["date"],
            "value": spot["value"] - contract_price["value"],
            "derived": True,
            "definition": "spot_minus_contract_settlement",
        }
    cash_cost = _number_from_value(
        fields["production_and_import_cost"].get("value"), "cash_cost", keys=("cash_cost", "value", "price")
    )
    full_cost = _number_from_value(
        fields["production_and_import_cost"].get("value"), "full_cost", keys=("full_cost", "value", "price")
    )
    inventory = _latest_series_number(observations.get("inventory", ()))
    exchange_inventory = _latest_series_number(observations.get("exchange_inventory", ()))
    warrants = _latest_series_number(observations.get("registered_warrants", ()))
    open_interest = _latest_series_number(observations.get("open_interest", ()))
    return {
        "spot_latest": spot,
        "contract_settlement_latest": contract_price,
        "basis_latest": basis,
        "inventory_latest": inventory,
        "inventory_change": _series_change(observations.get("inventory", ())),
        "exchange_inventory_latest": exchange_inventory,
        "registered_warrants_latest": warrants,
        "registered_warrants_change": _series_change(
            observations.get("registered_warrants", ())
        ),
        "open_interest_latest": open_interest,
        "cash_cost": cash_cost,
        "full_cost": full_cost,
        "spot_minus_cash_cost": _difference(spot, cash_cost),
        "spot_minus_full_cost": _difference(spot, full_cost),
        "contract_minus_spot": _difference(contract_price, spot),
        "calendar_spread_latest": _latest_series_number(
            observations.get("calendar_spread", ())
        ),
    }


def _build_variety_view(
    identity: Mapping[str, Any],
    fields: Mapping[str, Mapping[str, Any]],
    derived: Mapping[str, Any],
    assessments: Mapping[str, Any],
    gaps: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    status, reasons = _group_status(fields, _VARIETY_FIELDS)
    if str(identity.get("status") or "").upper() == "BLOCKED":
        status = "BLOCKED"
        reasons = ["FUTURES_IDENTITY_BLOCKED"]
    chain = identity.get("industry_chain")
    if not chain:
        reasons.append("INDUSTRY_CHAIN_NOT_SUPPLIED")
        if status == "READY":
            status = "PARTIAL"
    return {
        "status": status,
        "judgment": assessments.get("variety_bias", "NOT_ASSESSED"),
        "industry_chain": chain,
        "supply_demand_balance": _field_value(fields, "supply_demand_balance"),
        "production_and_utilization": _field_value(fields, "production_and_utilization"),
        "imports_exports": _field_value(fields, "imports_exports"),
        "inventory": {
            "by_location": _field_value(fields, "inventory_by_location"),
            "latest": derived.get("inventory_latest"),
            "change": derived.get("inventory_change"),
        },
        "cost_and_margin": {
            "cost": _field_value(fields, "production_and_import_cost"),
            "industry_margin": _field_value(fields, "industry_margin"),
            "spot_minus_cash_cost": derived.get("spot_minus_cash_cost"),
            "spot_minus_full_cost": derived.get("spot_minus_full_cost"),
        },
        "seasonality": _field_value(fields, "seasonality"),
        "evidence_gaps": [gap for gap in gaps if gap["field"] in _VARIETY_FIELDS],
        "conclusion_boundary": "品种判断只描述供需与成本证据，不等同于任意月份合约方向。",
    }


def _build_contract_view(
    identity: Mapping[str, Any],
    fields: Mapping[str, Mapping[str, Any]],
    observations: Mapping[str, Sequence[Mapping[str, Any]]],
    derived: Mapping[str, Any],
    assessments: Mapping[str, Any],
    gaps: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    object_type = str(identity.get("object_type") or "").lower()
    if object_type != "futures_contract":
        return {
            "status": "NOT_APPLICABLE",
            "judgment": "NOT_ASSESSED",
            "contract_bound": False,
            "reason": "只有具体月份合约才有合约相对价值和交割约束判断。",
            "missing_fields": list(_CONTRACT_FIELDS),
            "evidence_gaps": [],
        }
    status, reasons = _group_status(fields, _CONTRACT_FIELDS)
    if str(identity.get("status") or "").upper() != "READY":
        status = "INSUFFICIENT"
        reasons.insert(0, "FUTURES_IDENTITY_NOT_READY")
    contract = identity.get("contract") or {}
    if not observations.get("contract_settlement"):
        reasons.append("CONTRACT_SETTLEMENT_SERIES_NOT_SUPPLIED")
        if status == "READY":
            status = "PARTIAL"
    if not observations.get("basis"):
        reasons.append("BASIS_SERIES_NOT_SUPPLIED")
    if not observations.get("calendar_spread"):
        reasons.append("CALENDAR_SPREAD_SERIES_NOT_SUPPLIED")
    if status == "READY" and any(
        reason in {"BASIS_SERIES_NOT_SUPPLIED", "CALENDAR_SPREAD_SERIES_NOT_SUPPLIED"}
        for reason in reasons
    ):
        status = "PARTIAL"
    critical = {
        "spot_benchmark": _field_value(fields, "spot_benchmark"),
        "exchange_inventory_and_warrants": _field_value(
            fields, "exchange_inventory_and_warrants"
        ),
        "delivery_rules_and_warrant_expiry": _field_value(
            fields, "delivery_rules_and_warrant_expiry"
        ),
    }
    return {
        "status": status,
        "judgment": assessments.get("contract_relative_value", "NOT_ASSESSED"),
        "contract_bound": True,
        "contract_code": str(contract.get("contract_code") or ""),
        "contract_month": str(contract.get("contract_month") or ""),
        "last_trade_date": str(contract.get("last_trade_date") or ""),
        "contract_multiplier": contract.get("contract_multiplier"),
        "settlement_basis": contract.get("settlement_basis"),
        "spot_benchmark": critical["spot_benchmark"],
        "basis_and_calendar_spread": _field_value(
            fields, "basis_and_calendar_spread"
        ),
        "term_structure": _field_value(fields, "term_structure"),
        "latest": {
            "contract_settlement": derived.get("contract_settlement_latest"),
            "basis": derived.get("basis_latest"),
            "calendar_spread": derived.get("calendar_spread_latest"),
            "contract_minus_spot": derived.get("contract_minus_spot"),
        },
        "delivery": critical["delivery_rules_and_warrant_expiry"],
        "exchange_inventory_and_warrants": critical[
            "exchange_inventory_and_warrants"
        ],
        "open_interest": _field_value(
            fields, "open_interest_and_available_member_positions"
        ),
        "evidence_gaps": [gap for gap in gaps if gap["field"] in _CONTRACT_FIELDS],
        "reasons": list(dict.fromkeys(reasons)),
        "conclusion_boundary": "合约判断必须同时看到现货、库存/仓单、基差、期限结构和交割规则。",
    }


def _build_market_structure_view(report: Mapping[str, Any] | None) -> dict[str, Any]:
    if report is None:
        return {
            "status": "NOT_SUPPLIED",
            "implementation": None,
            "report_id": None,
            "signal": None,
            "interpretation": "市场结构未提供，只保留基本面研究，不影响品种与合约证据层。",
        }
    schema = str(report.get("schema_version") or "")
    status = "SUPPLIED"
    comparison = report.get("comparison")
    comparison_status = (
        comparison.get("status") if isinstance(comparison, Mapping) else report.get("status")
    )
    if schema == "market-structure-comparison.v1" and str(comparison_status or "") == "DIVERGENT":
        status = "REVIEW_REQUIRED"
    return {
        "status": status,
        "implementation": report.get("implementation") or report.get("implementations"),
        "report_id": report.get("report_id") or report.get("comparison_id"),
        "confirmation": report.get("confirmation"),
        "repaint_risk": report.get("repaint_risk"),
        "signal": None,
        "source_schema_version": schema,
        "interpretation": "市场结构仅作时点辅助；结构分歧降低置信度，不改变基本面结论。",
    }


def _build_simulation_view(
    identity: Mapping[str, Any],
    variety_view: Mapping[str, Any],
    contract_view: Mapping[str, Any],
    scenarios: Mapping[str, Any],
    market_structure: Mapping[str, Any],
) -> dict[str, Any]:
    blockers: list[str] = []
    identity_status = str(identity.get("status") or "BLOCKED").upper()
    if str(identity.get("object_type") or "").lower() != "futures_contract":
        blockers.append("SPECIFIC_CONTRACT_REQUIRED")
    if identity_status != "READY":
        blockers.append("FUTURES_IDENTITY_NOT_READY")
    if str(variety_view.get("status") or "") in {"BLOCKED", "INSUFFICIENT"}:
        blockers.append("VARIETY_EVIDENCE_INSUFFICIENT")
    if str(contract_view.get("status") or "") in {
        "NOT_APPLICABLE",
        "INSUFFICIENT",
    }:
        blockers.append("CONTRACT_VIEW_INSUFFICIENT")
    if scenarios.get("status") != "READY":
        blockers.append("PRICE_SCENARIOS_NOT_READY")
    if market_structure.get("status") == "REVIEW_REQUIRED":
        blockers.append("MARKET_STRUCTURE_DISAGREEMENT")
    blockers = list(dict.fromkeys(blockers))
    if blockers:
        status = "REVIEW_REQUIRED" if len(blockers) == 1 and blockers[0] == "PRICE_SCENARIOS_NOT_READY" else "INSUFFICIENT"
    else:
        status = "ELIGIBLE_FOR_USER_REVIEW"
    return {
        "status": status,
        "simulation_allowed_by_identity": bool(identity.get("simulation_allowed")),
        "user_confirmation_required": True,
        "action": "OBSERVE" if status != "ELIGIBLE_FOR_USER_REVIEW" else "USER_CONFIRMATION_REQUIRED",
        "direction": "NOT_ASSESSED",
        "price_scenarios": scenarios,
        "blockers": blockers,
        "market_structure_used_as_signal": False,
        "decision_snapshot_created": False,
        "conclusion_boundary": "此层只说明是否具备进入用户确认的模拟研究条件，不是下单指令。",
    }


def _build_phases(
    *,
    identity_report: Mapping[str, Any],
    object_type: str,
    fields: Mapping[str, Mapping[str, Any]],
    observations: Mapping[str, Sequence[Mapping[str, Any]]],
    scenarios: Mapping[str, Any],
    market_structure: Mapping[str, Any],
    variety_view: Mapping[str, Any],
    contract_view: Mapping[str, Any],
    simulation_view: Mapping[str, Any],
    field_gaps: Sequence[Mapping[str, Any]],
    as_of: date,
) -> dict[str, dict[str, Any]]:
    findings = _adversarial_findings(
        identity_report, fields, observations, contract_view, as_of
    )
    finding_status = "PASS" if not field_gaps else "REVIEW_REQUIRED"
    if any(item.get("severity") == "REVIEW" for item in findings):
        finding_status = "REVIEW_REQUIRED"
    return {
        "F1_identity_and_rules": {
            "status": str(identity_report.get("status") or "BLOCKED").upper(),
            "object_type": object_type,
            "exchange": identity_report.get("exchange"),
            "rule_version": identity_report.get("rule_version"),
            "research_only": bool(identity_report.get("research_only")),
        },
        "F2_spot_chain_and_indicator_map": {
            "status": variety_view["status"] if identity_report.get("industry_chain") else "PARTIAL",
            "industry_chain": identity_report.get("industry_chain"),
            "required_field": "spot_benchmark",
        },
        "F3_supply_and_demand": {
            "status": _group_status(fields, _VARIETY_FIELDS)[0],
            "fields": list(_VARIETY_FIELDS),
        },
        "F4_spot_inventory_warrants_cutoff": {
            "status": _group_status(
                fields,
                ("inventory_by_location", "exchange_inventory_and_warrants", "spot_benchmark"),
            )[0],
            "series": {
                name: len(observations.get(name, ()))
                for name in ("spot_price", "inventory", "exchange_inventory", "registered_warrants")
            },
        },
        "F5_cost_basis_term_structure": {
            "status": contract_view["status"] if object_type == "futures_contract" else variety_view["status"],
            "derived_metrics": [
                "spot_minus_cash_cost",
                "spot_minus_full_cost",
                "basis_latest",
                "calendar_spread_latest",
            ],
        },
        "F6_seasonality_delivery_and_warrant_expiry": {
            "status": _group_status(
                fields, ("seasonality", "delivery_rules_and_warrant_expiry")
            )[0],
            "delivery_rule_present": _present(
                fields["delivery_rules_and_warrant_expiry"].get("value")
            ),
        },
        "F7_price_scenarios": {
            "status": scenarios["status"],
            "scenario_names": list(_SCENARIOS),
            "observation_range_only": True,
        },
        "F8_market_structure_optional": {
            "status": market_structure["status"],
            "signal": None,
        },
        "F9_adversarial_review": {
            "status": finding_status,
            "findings": findings,
        },
        "F10_report_and_follow_up": {
            "status": simulation_view["status"],
            "evidence_gap_count": len(field_gaps),
            "follow_up": _follow_up(simulation_view, field_gaps),
        },
    }


def _adversarial_findings(
    identity: Mapping[str, Any],
    fields: Mapping[str, Mapping[str, Any]],
    observations: Mapping[str, Sequence[Mapping[str, Any]]],
    contract_view: Mapping[str, Any],
    as_of: date,
) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    if str(identity.get("object_type") or "").lower() in {
        "continuous_series",
        "spot_benchmark",
    }:
        findings.append(
            {
                "type": "RESEARCH_ONLY_OBJECT",
                "severity": "INFO",
                "message": "连续序列或现货基准不能绑定模拟成交。",
            }
        )
    if not observations.get("contract_settlement") and str(
        identity.get("object_type") or ""
    ).lower() == "futures_contract":
        findings.append(
            {
                "type": "CONTRACT_PRICE_MISSING",
                "severity": "REVIEW",
                "message": "未提供具体合约结算价序列，不能复核合约相对价值。",
            }
        )
    for name, field in fields.items():
        if field.get("status") == "CONFLICTING":
            findings.append(
                {
                    "type": "CONFLICTING_EVIDENCE",
                    "severity": "REVIEW",
                    "field": name,
                    "message": "字段来源存在冲突，未自动裁决。",
                }
            )
    if str(contract_view.get("last_trade_date") or ""):
        try:
            if _parse_date(contract_view["last_trade_date"], "last_trade_date") < as_of:
                findings.append(
                    {
                        "type": "EXPIRED_CONTRACT_AT_RUNTIME",
                        "severity": "REVIEW",
                        "message": "合约最后交易日早于当前运行日期，需按研究截面重新核对。",
                    }
                )
        except FuturesFundamentalsError:
            pass
    return findings


def _follow_up(
    simulation_view: Mapping[str, Any], gaps: Sequence[Mapping[str, Any]]
) -> list[str]:
    follow_up = []
    if simulation_view.get("status") != "ELIGIBLE_FOR_USER_REVIEW":
        follow_up.append("补齐阻塞条件后重新运行期货研究")
    for gap in gaps:
        follow_up.append(f"补充字段证据: {gap['field']}")
    return list(dict.fromkeys(follow_up))


def _group_status(
    fields: Mapping[str, Mapping[str, Any]], required: Sequence[str]
) -> tuple[str, list[str]]:
    reasons: list[str] = []
    statuses = []
    for field in required:
        status = str(fields.get(field, {}).get("status") or "MISSING").upper()
        statuses.append(status)
        if status == "MISSING":
            reasons.append(f"{field.upper()}_MISSING")
        elif status == "CONFLICTING":
            reasons.append(f"{field.upper()}_CONFLICTING")
        elif status in {"PARTIAL", "UNVERIFIED"}:
            reasons.append(f"{field.upper()}_{status}")
    if any(status in {"MISSING", "CONFLICTING"} for status in statuses):
        return "INSUFFICIENT", reasons
    if any(status in {"PARTIAL", "UNVERIFIED"} for status in statuses):
        return "PARTIAL", reasons
    return "READY", reasons


def _field_gaps(fields: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    gaps = []
    for field in FUNDAMENTAL_FIELDS:
        summary = fields[field]
        status = str(summary.get("status") or "MISSING").upper()
        if status != "VERIFIED":
            gaps.append(
                {
                    "field": field,
                    "status": status,
                    "reason": "FIELD_NOT_VERIFIED",
                    "evidence_ids": list(summary.get("evidence_ids") or []),
                }
            )
    return gaps


def _field_value(fields: Mapping[str, Mapping[str, Any]], name: str) -> dict[str, Any]:
    summary = fields.get(name) or {}
    return {
        "status": str(summary.get("status") or "MISSING"),
        "value": summary.get("value"),
        "unit": str(summary.get("unit") or ""),
        "evidence_ids": list(summary.get("evidence_ids") or []),
        "sources": list(summary.get("sources") or []),
        "as_of": list(summary.get("as_of") or []),
    }


def _latest_series_number(
    rows: Sequence[Mapping[str, Any]], *, contract_code: str = ""
) -> dict[str, Any] | None:
    candidates = []
    for row in rows:
        if contract_code and row.get("contract_code") and str(row["contract_code"]).upper() != contract_code.upper():
            continue
        value = _number_from_value(row, "value", keys=("value", "price", "settlement", "close", "amount"))
        if value is None:
            continue
        candidates.append({"date": str(row.get("date") or ""), "value": value})
    return candidates[-1] if candidates else None


def _series_change(rows: Sequence[Mapping[str, Any]]) -> dict[str, Any] | None:
    numeric = []
    for row in rows:
        value = _number_from_value(row, "value", keys=("value", "price", "settlement", "close", "amount"))
        if value is not None:
            numeric.append({"date": str(row.get("date") or ""), "value": value})
    if len(numeric) < 2:
        return None
    return {
        "from": numeric[0],
        "to": numeric[-1],
        "absolute": numeric[-1]["value"] - numeric[0]["value"],
        "percentage": (
            numeric[-1]["value"] / numeric[0]["value"] - 1
            if numeric[0]["value"] != 0
            else None
        ),
    }


def _difference(left: Mapping[str, Any] | None, right: float | Mapping[str, Any] | None) -> dict[str, Any] | None:
    if left is None or right is None:
        return None
    left_value = _number(left.get("value"), "left") if isinstance(left, Mapping) else None
    right_value = _number(right, "right") if not isinstance(right, Mapping) else _number(right.get("value"), "right")
    if left_value is None or right_value is None:
        return None
    return {"value": left_value - right_value, "left": left_value, "right": right_value}


def _number_from_value(value: Any, field: str, *, keys: Sequence[str] = ("value", "price", "amount")) -> float | None:
    if isinstance(value, Mapping):
        for key in keys:
            if key in value:
                number = _number(value.get(key), f"{field}.{key}")
                if number is not None:
                    return number
        return None
    return _number(value, field)


def _number(value: Any, field: str) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, bool):
        raise FuturesFundamentalsError(f"{field} must be numeric, not boolean")
    try:
        number = float(value)
    except (TypeError, ValueError) as error:
        raise FuturesFundamentalsError(f"{field} must be numeric") from error
    if not isfinite(number):
        raise FuturesFundamentalsError(f"{field} must be finite")
    return number


def _present(value: Any) -> bool:
    return value is not None and value != "" and value != [] and value != {}


def _overall_status(
    identity_status: str,
    variety_view: Mapping[str, Any],
    contract_view: Mapping[str, Any],
    simulation_view: Mapping[str, Any],
) -> str:
    if identity_status == "BLOCKED":
        return "BLOCKED"
    if simulation_view.get("status") == "ELIGIBLE_FOR_USER_REVIEW":
        return "READY"
    if variety_view.get("status") == "INSUFFICIENT":
        return "INSUFFICIENT"
    return "PARTIAL"


def _validate_market_structure(report: Mapping[str, Any]) -> None:
    if not isinstance(report, Mapping):
        raise FuturesFundamentalsError("market_structure_report must be an object")
    if report.get("schema_version") not in MARKET_STRUCTURE_SCHEMAS:
        raise FuturesFundamentalsError(
            "market_structure_report has an unsupported schema_version"
        )


def _reject_future(value: str, as_of: date, field: str) -> None:
    parsed = _parse_date(value, field)
    if parsed > as_of:
        raise FuturesFundamentalsError(
            f"future data exceeds as_of: {field}={value} > {as_of.isoformat()}"
        )


def _parse_date(value: Any, field: str) -> date:
    text = str(value or "").strip()
    if not text:
        raise FuturesFundamentalsError(f"{field} is required")
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).date()
    except ValueError:
        try:
            return date.fromisoformat(text)
        except ValueError as error:
            raise FuturesFundamentalsError(f"{field} must be ISO date/datetime") from error


def _string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value.strip() else []
    if not isinstance(value, Sequence) or isinstance(value, (bytes, bytearray)):
        raise FuturesFundamentalsError("expected a string or string list")
    return [str(item) for item in value if str(item).strip()]
